//
//  SuggestionView.swift
//  HandwritingToSpeechSwiftUI
//
//  Story 3.3: Suggestion Selection UI
//  Displays AI-generated suggestions and allows user to select one for TTS.
//

import SwiftUI
import UIKit

// MARK: - SuggestionCard Component

/// Individual suggestion card component (AC: 1, 5)
/// Follows SpeechShortcutsView button pattern with accessibility support.
/// Story 4.2: Added context menu for "More like this" (AC3)
@MainActor
struct SuggestionCard: View {
    let suggestion: String
    let onSelect: () -> Void
    let onMoreLikeThis: () -> Void

    var body: some View {
        Button(action: onSelect) {
            Text(suggestion)
                .font(.body)
                .multilineTextAlignment(.leading)
                .fixedSize(horizontal: false, vertical: true)
                .padding()
                .frame(maxWidth: .infinity, alignment: .leading)
                .background(Color(.systemGray6))
                .cornerRadius(12)
        }
        .buttonStyle(ScaleButtonStyle(scaleAmount: 0.97, pressedColor: .clear, normalColor: .clear))
        .accessibilityLabel(suggestion)
        .accessibilityHint("Double-tapez pour prononcer cette suggestion")
        // Story 4.2: Context menu for "More like this" (AC3)
        .contextMenu {
            Button {
                onMoreLikeThis()
            } label: {
                Label("Plus comme ça", systemImage: "plus.circle")
            }
        }
    }
}

// MARK: - SuggestionView Main Component

/// Main suggestion display component (AC: 1, 2, 3, 4, 5)
/// Displays suggestions generated by SuggestionService and handles selection/dismissal.
@MainActor
struct SuggestionView: View {
    // M2 Fix: Use @ObservedObject for shared singleton (not @StateObject which implies ownership)
    @ObservedObject private var suggestionService = SuggestionService.shared
    @EnvironmentObject var speechService: SpeechService

    /// Current text for generating new suggestions
    var currentText: String

    /// Callback when suggestion is selected (optional, for additional actions)
    var onSuggestionSelected: ((String) -> Void)?

    var body: some View {
        // AC1, AC4: Only show when suggestions available or loading
        if !suggestionService.suggestions.isEmpty || suggestionService.isLoading {
            VStack(alignment: .leading, spacing: 12) {
                // Header with title and action buttons
                headerView

                // AC4: Loading indicator
                if suggestionService.isLoading {
                    loadingView
                }

                // AC1: Suggestion cards list
                if !suggestionService.suggestions.isEmpty {
                    suggestionsList
                }
            }
            .padding()
            .background(Color(.systemGray6).opacity(0.5))
            .cornerRadius(12)
            .padding(.horizontal)
            // M1 Fix: VoiceOver focus order - suggestions container is a logical group
            .accessibilityElement(children: .contain)
            .accessibilityLabel("Zone de suggestions IA")
        }
    }

    // MARK: - Header View

    private var headerView: some View {
        HStack {
            Text("Suggestions IA")
                .font(.headline)
                .foregroundColor(.secondary)

            Spacer()

            // Story 4.2: "Different" button (AC4)
            Button(action: generateDifferent) {
                HStack(spacing: 4) {
                    Image(systemName: "shuffle")
                        .font(.system(size: 12, weight: .medium))
                    Text("Autre")
                        .font(.caption)
                }
                .foregroundColor(.secondary)
                .padding(.horizontal, 10)
                .padding(.vertical, 6)
                .background(Color(.systemGray5))
                .cornerRadius(8)
            }
            .buttonStyle(ScaleButtonStyle(scaleAmount: 0.9, pressedColor: .clear, normalColor: .clear))
            .disabled(suggestionService.isLoading || suggestionService.suggestions.isEmpty)
            .opacity(suggestionService.isLoading || suggestionService.suggestions.isEmpty ? 0.4 : 1.0)
            .accessibilityLabel("Autres suggestions")
            .accessibilityHint("Génère des suggestions complètement différentes")

            // AC3: Refresh button
            Button(action: refreshSuggestions) {
                Image(systemName: "arrow.clockwise")
                    .font(.system(size: 16, weight: .medium))
                    .foregroundColor(.secondary)
                    .frame(width: 32, height: 32)
                    .background(Color(.systemGray5))
                    .cornerRadius(8)
            }
            .buttonStyle(ScaleButtonStyle(scaleAmount: 0.9, pressedColor: .clear, normalColor: .clear))
            .disabled(suggestionService.isLoading || currentText.isEmpty)
            // L3 Fix: Visual indication when disabled
            .opacity(suggestionService.isLoading || currentText.isEmpty ? 0.4 : 1.0)
            .accessibilityLabel("Rafraîchir les suggestions")
            .accessibilityHint(currentText.isEmpty
                ? "Entrez du texte pour pouvoir rafraîchir les suggestions"
                : "Génère de nouvelles suggestions basées sur le texte actuel")

            // AC3: Dismiss button
            Button(action: dismissSuggestions) {
                Image(systemName: "xmark")
                    .font(.system(size: 14, weight: .medium))
                    .foregroundColor(.secondary)
                    .frame(width: 32, height: 32)
                    .background(Color(.systemGray5))
                    .cornerRadius(8)
            }
            .buttonStyle(ScaleButtonStyle(scaleAmount: 0.9, pressedColor: .clear, normalColor: .clear))
            .accessibilityLabel("Fermer les suggestions")
            .accessibilityHint("Masque les suggestions pour continuer à taper")
        }
    }

    // MARK: - Loading View

    private var loadingView: some View {
        HStack {
            ProgressView()
                .scaleEffect(0.8)
            Text("Chargement des suggestions...")
                .font(.caption)
                .foregroundColor(.secondary)
        }
        .padding(.vertical, 8)
        .accessibilityLabel("Chargement des suggestions en cours")
    }

    // MARK: - Suggestions List

    private var suggestionsList: some View {
        VStack(spacing: 8) {
            ForEach(suggestionService.suggestions, id: \.self) { suggestion in
                SuggestionCard(
                    suggestion: suggestion,
                    onSelect: { selectSuggestion(suggestion) },
                    onMoreLikeThis: { moreLikeThis(suggestion) }
                )
            }
        }
    }

    // MARK: - Actions

    /// AC2: Handles suggestion selection with haptic feedback and TTS
    private func selectSuggestion(_ suggestion: String) {
        // Haptic feedback
        let impact = UIImpactFeedbackGenerator(style: .medium)
        impact.impactOccurred()

        // Speak the suggestion via TTS
        speechService.speakText(suggestion)

        // Add to conversation history for context-aware future suggestions
        suggestionService.addToHistory(userMessage: suggestion)

        // Notify callback if provided
        onSuggestionSelected?(suggestion)

        // Clear suggestions after selection
        suggestionService.clearSuggestions()

        // L1 Fix: Removed debug print statement from production code
    }

    /// AC3: Refreshes suggestions based on current text
    private func refreshSuggestions() {
        guard !currentText.isEmpty else { return }

        Task {
            await suggestionService.generateSuggestions(for: currentText)
        }
    }

    /// AC3: Dismisses suggestions to allow manual typing
    private func dismissSuggestions() {
        suggestionService.clearSuggestions()
    }

    // MARK: - Story 4.2: Guidance Actions

    /// Story 4.2 AC4: Generates completely different suggestions
    private func generateDifferent() {
        // H2 Fix: Add haptic feedback (Task 5 requirement)
        let impact = UIImpactFeedbackGenerator(style: .light)
        impact.impactOccurred()
        Task {
            await suggestionService.generateDifferentSuggestions()
        }
    }

    /// Story 4.2 AC3: Generates variations of a specific suggestion ("More like this")
    private func moreLikeThis(_ suggestion: String) {
        let impact = UIImpactFeedbackGenerator(style: .light)
        impact.impactOccurred()
        Task {
            await suggestionService.generateVariations(of: suggestion)
        }
    }
}

// MARK: - Generate Suggestions Button

/// Button to trigger suggestion generation (for integration in ContentView)
@MainActor
struct GenerateSuggestionsButton: View {
    // M2 Fix: Use @ObservedObject for shared singleton (not @StateObject which implies ownership)
    @ObservedObject private var suggestionService = SuggestionService.shared
    var currentText: String

    var body: some View {
        Button(action: generateSuggestions) {
            HStack {
                if suggestionService.isLoading {
                    ProgressView()
                        .scaleEffect(0.8)
                        .tint(.white)
                } else {
                    Image(systemName: "sparkles")
                        .font(.system(size: 16))
                }
                Text("Suggestions IA")
                    .font(.subheadline)
                    .fontWeight(.medium)
            }
            .foregroundColor(.white)
            .padding(.horizontal, 16)
            .padding(.vertical, 10)
            .background(
                LinearGradient(
                    gradient: Gradient(colors: [Color.indigo, Color.indigo.opacity(0.8)]),
                    startPoint: .top,
                    endPoint: .bottom
                )
            )
            .cornerRadius(10)
        }
        .buttonStyle(ScaleButtonStyle(scaleAmount: 0.95, pressedColor: .clear, normalColor: .clear))
        .disabled(suggestionService.isLoading || currentText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty)
        .accessibilityLabel("Générer des suggestions IA")
        .accessibilityHint("Demande des suggestions de réponse basées sur le texte actuel")
    }

    private func generateSuggestions() {
        Task {
            await suggestionService.generateSuggestions(for: currentText)
        }
    }
}
