//
//  SuggestionView.swift
//  HandwritingToSpeechSwiftUI
//
//  Story 3.3: Suggestion Selection UI
//  Displays AI-generated suggestions and allows user to select one for TTS.
//

import SwiftUI
import UIKit

// MARK: - SuggestionCard Component

/// Individual suggestion card component (AC: 1, 5)
/// Follows SpeechShortcutsView button pattern with accessibility support.
/// Story 4.2: Added context menu for "More like this" (AC3)
/// InvincibleVoice: Added edit callback for copying suggestion to text field.
@MainActor
struct SuggestionCard: View {
    let suggestion: String
    let onSelect: () -> Void
    let onMoreLikeThis: () -> Void
    let onEdit: () -> Void

    var body: some View {
        HStack(spacing: 8) {
            // Main suggestion button
            Button(action: onSelect) {
                Text(suggestion)
                    .font(.body)
                    .multilineTextAlignment(.leading)
                    .fixedSize(horizontal: false, vertical: true)
                    .padding()
                    .frame(maxWidth: .infinity, alignment: .leading)
            }
            .buttonStyle(ScaleButtonStyle(scaleAmount: 0.97, pressedColor: .clear, normalColor: .clear))
            .accessibilityLabel(suggestion)
            .accessibilityHint("Double-tapez pour prononcer cette suggestion")

            // InvincibleVoice: Edit button
            // F4 Fix: Minimum 44x44 tap target per Apple HIG
            Button(action: onEdit) {
                Image(systemName: "pencil")
                    .font(.system(size: 16, weight: .medium))
                    .foregroundColor(.secondary)
                    .frame(width: 44, height: 44)
                    .background(Color(.systemGray5))
                    .cornerRadius(8)
            }
            .buttonStyle(ScaleButtonStyle(scaleAmount: 0.9, pressedColor: .clear, normalColor: .clear))
            .accessibilityLabel("Éditer")
            .accessibilityHint("Copie la suggestion dans le champ de texte pour modification")
        }
        .padding(.trailing, 8)
        .background(Color(.systemGray6))
        .cornerRadius(12)
        // Story 4.2: Context menu for "More like this" (AC3)
        .contextMenu {
            Button {
                onMoreLikeThis()
            } label: {
                Label("Plus comme ça", systemImage: "plus.circle")
            }
            Button {
                onEdit()
            } label: {
                Label("Éditer", systemImage: "pencil")
            }
        }
    }
}

// MARK: - SuggestionView Main Component

/// Main suggestion display component (AC: 1, 2, 3, 4, 5)
/// Displays suggestions generated by SuggestionService and handles selection/dismissal.
/// InvincibleVoice: Added edit callback for copying suggestion to text field.
@MainActor
struct SuggestionView: View {
    // M2 Fix: Use @ObservedObject for shared singleton (not @StateObject which implies ownership)
    @ObservedObject private var suggestionService = SuggestionService.shared
    @EnvironmentObject var speechService: SpeechService

    /// Current text for generating new suggestions
    var currentText: String

    /// Callback when suggestion is selected (optional, for additional actions)
    var onSuggestionSelected: ((String) -> Void)?

    /// InvincibleVoice: Callback when edit button is tapped (copies suggestion to text field)
    var onEditSuggestion: ((String) -> Void)?

    var body: some View {
        // AC1, AC4: Only show when suggestions available or loading
        if !suggestionService.suggestions.isEmpty || suggestionService.isLoading {
            VStack(alignment: .leading, spacing: 12) {
                // Header with title and action buttons
                headerView

                // AC4: Loading indicator
                if suggestionService.isLoading {
                    loadingView
                }

                // AC1: Suggestion cards list
                if !suggestionService.suggestions.isEmpty {
                    suggestionsList
                }
            }
            .padding()
            .background(Color(.systemGray6).opacity(0.5))
            .cornerRadius(12)
            .padding(.horizontal)
            // M1 Fix: VoiceOver focus order - suggestions container is a logical group
            .accessibilityElement(children: .contain)
            .accessibilityLabel("Zone de suggestions IA")
        }
    }

    // MARK: - Header View

    // Story 5.3: Added spacing: 12 for accessibility (AC3)
    private var headerView: some View {
        HStack(spacing: 12) {
            Text("Suggestions IA")
                .font(.headline)
                .foregroundColor(.secondary)

            // F3 Fix: Visual indicator when suggestions are frozen (edit mode)
            if suggestionService.isEditingText {
                Text("(en édition)")
                    .font(.caption)
                    .foregroundColor(.orange)
                    .padding(.horizontal, 6)
                    .padding(.vertical, 2)
                    .background(Color.orange.opacity(0.15))
                    .cornerRadius(4)
            }

            Spacer()

            // Story 4.2: "Different" button (AC4)
            // Story 5.3: Enlarged touch target to min 44pt height (AC4)
            Button(action: generateDifferent) {
                HStack(spacing: 4) {
                    Image(systemName: "shuffle")
                        .font(.system(size: 14, weight: .medium))  // Story 5.3: Increased from 12pt (proportional)
                    Text("Autre")
                        .font(.caption)
                }
                .foregroundColor(.secondary)
                .padding(.horizontal, 12)  // Story 5.3: Increased from 10pt (proportional)
                .padding(.vertical, 12)  // Story 5.3: Increased from 6pt (AC4)
                .background(Color(.systemGray5))
                .cornerRadius(10)  // Story 5.3: Proportional increase from 8pt
                .frame(minHeight: 44)  // Story 5.3: Explicit 44pt minimum (AC4)
            }
            .buttonStyle(ScaleButtonStyle(scaleAmount: 0.9, pressedColor: .clear, normalColor: .clear))
            .disabled(suggestionService.isLoading || suggestionService.suggestions.isEmpty)
            .opacity(suggestionService.isLoading || suggestionService.suggestions.isEmpty ? 0.4 : 1.0)
            .accessibilityLabel("Autres suggestions")
            .accessibilityHint("Génère des suggestions complètement différentes")

            // AC3: Refresh button
            // Story 5.3: Enlarged touch target to 44x44pt (AC1)
            Button(action: refreshSuggestions) {
                Image(systemName: "arrow.clockwise")
                    .font(.system(size: 18, weight: .medium))  // Story 5.3: Increased from 16pt (proportional)
                    .foregroundColor(.secondary)
                    .frame(width: 44, height: 44)  // Story 5.3: Increased from 32pt (AC1)
                    .background(Color(.systemGray5))
                    .cornerRadius(10)  // Story 5.3: Proportional increase from 8pt
            }
            .buttonStyle(ScaleButtonStyle(scaleAmount: 0.9, pressedColor: .clear, normalColor: .clear))
            .disabled(suggestionService.isLoading || currentText.isEmpty)
            // L3 Fix: Visual indication when disabled
            .opacity(suggestionService.isLoading || currentText.isEmpty ? 0.4 : 1.0)
            .accessibilityLabel("Rafraîchir les suggestions")
            .accessibilityHint(currentText.isEmpty
                ? "Entrez du texte pour pouvoir rafraîchir les suggestions"
                : "Génère de nouvelles suggestions basées sur le texte actuel")

            // AC3: Dismiss button
            // Story 5.3: Enlarged touch target to 44x44pt (AC2)
            Button(action: dismissSuggestions) {
                Image(systemName: "xmark")
                    .font(.system(size: 16, weight: .medium))  // Story 5.3: Increased from 14pt (proportional)
                    .foregroundColor(.secondary)
                    .frame(width: 44, height: 44)  // Story 5.3: Increased from 32pt (AC2)
                    .background(Color(.systemGray5))
                    .cornerRadius(10)  // Story 5.3: Proportional increase from 8pt
            }
            .buttonStyle(ScaleButtonStyle(scaleAmount: 0.9, pressedColor: .clear, normalColor: .clear))
            .accessibilityLabel("Fermer les suggestions")
            .accessibilityHint("Masque les suggestions pour continuer à taper")
        }
    }

    // MARK: - Loading View

    private var loadingView: some View {
        HStack {
            ProgressView()
                .scaleEffect(0.8)
            Text("Chargement des suggestions...")
                .font(.caption)
                .foregroundColor(.secondary)
        }
        .padding(.vertical, 8)
        .accessibilityLabel("Chargement des suggestions en cours")
    }

    // MARK: - Suggestions List

    private var suggestionsList: some View {
        VStack(spacing: 8) {
            ForEach(suggestionService.suggestions, id: \.self) { suggestion in
                SuggestionCard(
                    suggestion: suggestion,
                    onSelect: { selectSuggestion(suggestion) },
                    onMoreLikeThis: { moreLikeThis(suggestion) },
                    onEdit: { editSuggestion(suggestion) }
                )
            }
        }
    }

    // MARK: - Actions

    /// AC2: Handles suggestion selection with haptic feedback and TTS
    private func selectSuggestion(_ suggestion: String) {
        // Haptic feedback
        let impact = UIImpactFeedbackGenerator(style: .medium)
        impact.impactOccurred()

        // Speak the suggestion via TTS
        speechService.speakText(suggestion)

        // Add to conversation history for context-aware future suggestions
        suggestionService.addToHistory(userMessage: suggestion)

        // Notify callback if provided
        onSuggestionSelected?(suggestion)

        // Clear suggestions after selection
        suggestionService.clearSuggestions()

        // L1 Fix: Removed debug print statement from production code
    }

    /// AC3: Refreshes suggestions based on current text
    private func refreshSuggestions() {
        guard !currentText.isEmpty else { return }

        Task {
            await suggestionService.generateSuggestions(for: currentText)
        }
    }

    /// AC3: Dismisses suggestions to allow manual typing
    private func dismissSuggestions() {
        suggestionService.clearSuggestions()
    }

    // MARK: - Story 4.2: Guidance Actions

    /// Story 4.2 AC4: Generates completely different suggestions
    private func generateDifferent() {
        // H2 Fix: Add haptic feedback (Task 5 requirement)
        // Story 5.3: Upgraded haptic from .light to .medium for accessibility
        let impact = UIImpactFeedbackGenerator(style: .medium)
        impact.impactOccurred()
        Task {
            await suggestionService.generateDifferentSuggestions()
        }
    }

    /// Story 4.2 AC3: Generates variations of a specific suggestion ("More like this")
    /// F5 Fix: Skip if in edit mode (suggestions frozen)
    private func moreLikeThis(_ suggestion: String) {
        // F5 Fix: Guard against frozen state
        guard !suggestionService.isEditingText else { return }
        // Story 5.3: Upgraded haptic from .light to .medium for accessibility consistency
        let impact = UIImpactFeedbackGenerator(style: .medium)
        impact.impactOccurred()
        Task {
            await suggestionService.generateVariations(of: suggestion)
        }
    }

    // MARK: - InvincibleVoice: Edit Mode Actions

    /// InvincibleVoice: Copies suggestion to text field for editing.
    /// Freezes suggestions to prevent auto-refresh during editing.
    private func editSuggestion(_ suggestion: String) {
        // Story 5.3: Upgraded haptic from .light to .medium for accessibility consistency
        let impact = UIImpactFeedbackGenerator(style: .medium)
        impact.impactOccurred()

        // Freeze suggestions (prevent auto-refresh during editing)
        suggestionService.freezeSuggestions()

        // Notify callback to copy suggestion to text field
        onEditSuggestion?(suggestion)
    }
}

// MARK: - Generate Suggestions Button

/// Button to trigger suggestion generation (for integration in ContentView)
@MainActor
struct GenerateSuggestionsButton: View {
    // M2 Fix: Use @ObservedObject for shared singleton (not @StateObject which implies ownership)
    @ObservedObject private var suggestionService = SuggestionService.shared
    var currentText: String

    var body: some View {
        Button(action: generateSuggestions) {
            HStack {
                if suggestionService.isLoading {
                    ProgressView()
                        .scaleEffect(0.8)
                        .tint(.white)
                } else {
                    Image(systemName: "sparkles")
                        .font(.system(size: 16))
                }
                Text("Suggestions IA")
                    .font(.subheadline)
                    .fontWeight(.medium)
            }
            .foregroundColor(.white)
            .padding(.horizontal, 16)
            .padding(.vertical, 10)
            .background(
                LinearGradient(
                    gradient: Gradient(colors: [Color.indigo, Color.indigo.opacity(0.8)]),
                    startPoint: .top,
                    endPoint: .bottom
                )
            )
            .cornerRadius(10)
        }
        .buttonStyle(ScaleButtonStyle(scaleAmount: 0.95, pressedColor: .clear, normalColor: .clear))
        .disabled(suggestionService.isLoading || currentText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty)
        .accessibilityLabel("Générer des suggestions IA")
        .accessibilityHint("Demande des suggestions de réponse basées sur le texte actuel")
    }

    private func generateSuggestions() {
        Task {
            await suggestionService.generateSuggestions(for: currentText)
        }
    }
}
